services:
  pgvector:
    image: ankane/pgvector:latest
    container_name: rag_pgvector
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ragpw
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: